### ISSUE TITLE
Not clear about what this package provides

### ISSUE THREAD

**Issue by drjasonharrison** [rcmdnk/pyproject-pre-commit#155]
I'm confused about what this package provides. The readme has:

```
pre-commit hooks for python projects using pyproject.toml.

.pre-commit-hooks.yaml provides pre-defined ids which you just need to add these ids to your .pre-commit-config.yaml.
```

So, by installing this project I get the pre-defined ids for python development? But I still need to create the .pre-commit-config.yaml. I still need to install pre-commit, and still need to run `pre-commit install....`

Is it the `pyproject.toml` feature? For example `flake8` uses `.flake8` but `pyproject-flake8` can get configuration data from `pyproject.toml`...

**Comment by rcmdnk** [comment]
The README was not so clear, sorry.

I have updated the README.
If you still have questions, please don't hesitate to ask.

pyproject-pre-commit provides 2 features:

* ids for tools
    * By adding `- repo: https://github.com/rcmdnk/pyproject-pre-commit` to your **.pre-commit-config.yaml**, you can easily add python related hooks, such as black, isort, mypy, and etc. (No need to add other repo)
    * This does not require **pyproject-pre-commit** package installation.
* tool installation
    * By installing **pyproject-pre-commit**, tools such as black, isort, or mypy will be installed.
    * You can use these tools directly from command line.

> So, by installing this project I get the pre-defined ids for python development?

To use ids, you don't need to install  **pyproject-pre-commit**.

Ids are available under `- repo: https://github.com/rcmdnk/pyproject-pre-commit`.

> But I still need to create the .pre-commit-config.yaml.

Yes, you need to create the .pre-commit-config.yaml.

> I still need to install pre-commit

If you install **pyproject-pre-commit**, `pre-commit` is also installed.

> and still need to run pre-commit install....

Yes, `pre-commit install` is needed.

> For example flake8 uses .flake8 but pyproject-flake8 can get configuration data from pyproject.toml...

This is intended. I want to summarize all configurations in pyproject.toml
and then pyproject-flake8 is used in **pyproject-pre-commit**.

You may just migrate configurations from .flake8 to pyproject.toml.

If you want to use .flake8, you may need original [flake8 pre-commit hook](https://github.com/PyCQA/flake8/blob/main/.pre-commit-hooks.yaml).

**Comment by drjasonharrison** [comment]
Ah, so this is (1) a collection of Python pre-commit hooks which if used reduces the need for a bunch of step by step entries in a .pre-commit-config.yaml (repo, id , version,... becomes one repo and lines of id.)

Plus a set of command line tools that overlaps with the above hooks.

Upside: fewer entries on extras_require for the dev environment. Fewer lines in the .pre-commit-config.yaml

Downside: uncertainty if the versions specified will be updated or reflect python versions. This occurs with individual hooks too. 

Thank you for the explanation!
